// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzlbitiwaeekuakwrkqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6bGJpdGl3YWVla3Vha3dya3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjY4MzksImV4cCI6MjA2Mzk0MjgzOX0.EHLXwqq9RCDCwOIXvu_8hN9dircKUvUzG9PsOcgj1GY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);